#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import the official Agent selection-to-handler-index methods unchanged."""
import hashlib
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
source = pathlib.Path(sys.argv[1]) / 'CPP/7zip/UI/Agent/Agent.cpp'
expected = '337ec0bdca12a34c53e361bc6cf42b6adb572c29a97e53b13e833fe838c772b0'
raw = source.read_bytes()
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit('Not the pinned official 26.03 Agent.cpp')
text = raw.decode('utf-8').replace('\r\n', '\n')
start = text.index('int CAgentFolder::GetRealIndex(')
body = text[start:text.index('Z7_COM7F_IMF(CAgentFolder::Extract(', start)].rstrip()
body = body.replace('CAgentFolder::', 'PortAgentFolder::')
header = ('// Agent.cpp\n'
          '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          '// Generated by scripts/import-agent-selection.py from official 7-Zip 26.03.\n'
          '// GetRealIndex/GetRealIndices bodies; class name adapted only.\n'
          '// Original source SHA-256: ' + expected + '\n\n')
destination = root / 'src/upstream/AgentSelection.inc'
content = (header + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    destination.write_bytes(content)
print(destination)
