#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import the official FILETIME formatter and menu precision choices."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
hashes = {
    'CPP/Windows/PropVariantConv.cpp': source_hash('CPP/Windows/PropVariantConv.cpp'),
    'CPP/Windows/PropVariantConv.h': source_hash('CPP/Windows/PropVariantConv.h'),
    'CPP/7zip/UI/FileManager/MyLoadMenu.cpp': source_hash('CPP/7zip/UI/FileManager/MyLoadMenu.cpp'),
}
texts = {}
header = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}; generated by scripts/import-time-menu.py.\n'
for name, digest in hashes.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest: parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
source = texts['CPP/Windows/PropVariantConv.cpp']
start = source.index('bool ConvertUtcFileTimeToString2(const FILETIME &utc, unsigned ns100, char *s, int level, unsigned flags) throw()')
end = source.index('\n\n\n', source.index('\n  return true;\n}', start))
constants = '\n'.join(line for line in texts['CPP/Windows/PropVariantConv.h'].splitlines() if line.startswith('#define kTimestampPrint'))
macro = next(line for line in source.splitlines() if line.startswith('#define UINT_TO_STR_2'))
menu = texts['CPP/7zip/UI/FileManager/MyLoadMenu.cpp']
start_levels = menu.index('        const int k_TimeLevels[]')
end_levels = menu.index('};', start_levels) + 2
levels = menu[start_levels:end_levels]
target = output_root() / 'src/upstream/TimeText.inc'
write_generated(target, header + '\n' + constants + '\n' + macro + '\n' + source[start:end] + '\n' + levels + '\n')
