#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import the official FILETIME formatter and menu precision choices."""
import argparse
import hashlib
import re
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
hashes = {
    'CPP/Windows/PropVariantConv.cpp': '89095bbf7807c53630c76c2f60e5d36c9f9dc768fad4898dee3008b5f93c5af7',
    'CPP/Windows/PropVariantConv.h': 'd2d674d343c16ba54cdd38d821b81eb1a10c5cfd6a3c5c79f78e3eb0e71adeed',
    'CPP/7zip/UI/FileManager/MyLoadMenu.cpp': '6a75a8267d755324baf30b47b01b191e97c05f3c48b3bc45ceee3c2d1dd02da5',
}
texts = {}
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03; generated by scripts/import-time-menu.py.\n'
for name, digest in hashes.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest: parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
source = texts['CPP/Windows/PropVariantConv.cpp']
start = source.index('bool ConvertUtcFileTimeToString2(const FILETIME &utc, unsigned ns100, char *s, int level, unsigned flags) throw()')
end = source.index('\n\n\n', source.index('\n  return true;\n}', start))
constants = '\n'.join(line for line in texts['CPP/Windows/PropVariantConv.h'].splitlines() if line.startswith('#define kTimestampPrint'))
macro = next(line for line in source.splitlines() if line.startswith('#define UINT_TO_STR_2'))
menu = texts['CPP/7zip/UI/FileManager/MyLoadMenu.cpp']
start_levels = menu.index('        const int k_TimeLevels[]')
end_levels = menu.index('};', start_levels) + 2
levels = menu[start_levels:end_levels]
target = Path(__file__).resolve().parents[1] / 'src/upstream/TimeText.inc'
target.write_text(header + '\n' + constants + '\n' + macro + '\n' + source[start:end] + '\n' + levels + '\n')
