#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official panel ordering, column policy and typed comparisons."""
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
hashes = {
    'CPP/7zip/UI/FileManager/PanelSort.cpp': '30bc0819c8eb7b8633d4bb0cbd55c903bfe3f374e9ee89230a3b6c32226318a1',
    'CPP/7zip/UI/FileManager/PanelItems.cpp': '2dc5869e794788b366b1dc7fb6485b362e7b72352c1549303b944693765e2f73',
    'CPP/7zip/UI/FileManager/FSFolder.cpp': '59ff062ca1c186410c76d9d1f50992f865d37d7cce948d236f4a7e00a13823bd',
    'CPP/7zip/PropID.h': '9a818538a047edf80583a479436b49575dd0c18b5ed7148574a24c5b67bfc53d',
    'CPP/Windows/PropVariant.cpp': '72c25c01b9d1e831f7ab51bbfb0f5b2c235b247af97895b6625144c39b894b57',
    'CPP/Windows/PropVariant.h': 'd7f4863aed432b0bfe3ac4f03f933a68937f73e50648f918fae512bece55e1d3',
    'CPP/Windows/FileFind.cpp': '98280cf2370f2fa243b41f79a68b1b20b5120167a80a355d1ae1100f71c40eab',
    'CPP/Common/MyString.cpp': 'ddb3751cfdcc60ed184f20e94732a1934472ce7cbcf87c40ac8d8b91d5f1b9d8',
    'CPP/7zip/UI/Common/PropIDUtils.cpp': 'de35cba611f5e44f3a3b04f2c66b5c34f89fca1ece2cef2a897a33efd5b81044',
}
texts = {}
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03; generated by scripts/import-panel-sort.py.\n'
for name, digest in hashes.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'

def function(text, signature, last=False):
    start = text.rindex(signature) if last else text.index(signature)
    brace = text.index('{', start)
    level = 1
    end = brace + 1
    while level:
        level += (text[end] == '{') - (text[end] == '}')
        end += 1
    return text[start:end]

sort = texts['CPP/7zip/UI/FileManager/PanelSort.cpp']
items = texts['CPP/7zip/UI/FileManager/PanelItems.cpp']
variant = texts['CPP/Windows/PropVariant.cpp']
chunks = [function(sort, 'int CompareFileNames_ForFolderList('),
          function(sort, 'static int CompareFileNames_Le16('),
          function(texts['CPP/Common/MyString.cpp'], 'int MyStringCompareNoCase(const wchar_t *'),
          function(variant, 'int CPropVariant::Compare('),
          function(sort, 'int CALLBACK CompareItems(LPARAM lParam1, LPARAM lParam2, LPARAM lpData)\n'),
          function(sort, 'void CPanel::SortItemsWithPropID(', last=True),
          function(items, 'static bool GetColumnVisible('),
          function(items, 'static unsigned GetColumnWidth('),
          function(items, 'static int GetColumnAlign('),
          function(texts['CPP/Windows/FileFind.cpp'], 'UInt32 Get_WinAttribPosix_From_PosixMode(')]
attributes = texts['CPP/7zip/UI/Common/PropIDUtils.cpp']
chunks.append(attributes[attributes.index('static const unsigned kNumWinAtrribFlags'):attributes.index('\n\n\nvoid ConvertPropertyToShortString2')])
variant_header = texts['CPP/Windows/PropVariant.h']
chunks.insert(0, function(variant_header, 'unsigned Get_Ns100() const'))
propids = texts['CPP/7zip/PropID.h']
enum_start = propids.index('enum\n{')
enum_end = propids.index('};', enum_start) + 2
target = Path(__file__).resolve().parents[1] / 'src/upstream'
outputs = {
    'PanelSortIds.h': '#pragma once\nnamespace OfficialSort {\n' + propids[enum_start:enum_end] + '\n}\n',
    'PanelSort.inc': '\n\n'.join(chunks[1:]) + '\n',
    'SortTimePrecision.inc': chunks[0] + '\n',
}
# The original filesystem schema, including optional file-identity columns.
fs = texts['CPP/7zip/UI/FileManager/FSFolder.cpp']
start = fs.index('static const Byte kProps[]')
end = fs.index('};', start) + 2
outputs['FilesystemColumns.inc'] = fs[start:end] + '\n'
for name, body in outputs.items():
    path = target / name
    content = (header + '\n' + body).encode()
    if not path.exists() or path.read_bytes() != content:
        path.write_bytes(content)
