#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import unchanged original Copy/Combine summary formatting functions."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
hashes = {'App.cpp': source_hash('CPP/7zip/UI/FileManager/App.cpp'), 'PanelSplitFile.cpp': source_hash('CPP/7zip/UI/FileManager/PanelSplitFile.cpp')}
texts = {}
notice = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}; generated by scripts/import-copy-info.py.\n'
for name, expected in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        parser.error('Unsupported original source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + expected + '\n'
def function(text, signature):
    start = text.index(signature); cursor = text.index('{', start) + 1; depth = 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}'); cursor += 1
    return text[start:cursor]
body = '\n'.join(function(texts['App.cpp'], signature) for signature in ['static void AddSizeValue(', 'static void AddValuePair1(', 'void AddValuePair2(UString &s, UINT resourceID, UInt64 num, UInt64 size)\n{', 'UString CPanel::GetItemsInfoString('])
body += '\n' + function(texts['PanelSplitFile.cpp'], 'static void AddInfoFileName(')
write_generated(output_root() / 'src/upstream/CopyInfo.inc', notice + body + '\n')
