#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import the original bounded temporary-folder enumerator."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import hashlib
import pathlib
import sys

root = output_root()
source = pathlib.Path(sys.argv[1]) / 'CPP/7zip/UI/FileManager/BrowseDialog2.cpp'
expected = source_hash('CPP/7zip/UI/FileManager/BrowseDialog2.cpp')
raw = source.read_bytes()
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit(f'Not the pinned official {VERSION} BrowseDialog2.cpp')
text = raw.decode('utf-8').replace('\r\n', '\n')
start = text.index('static const UInt32 k_EnumerateDirsLimit')
body = text[start:text.index('class CBrowseDialog2:', start)].rstrip()
assert body.count('fi.HasReparsePoint()') == 1
body = body.replace('fi.HasReparsePoint()', 'fi.IsOsSymLink()')
size_source = source.with_name('BrowseDialog.cpp')
size_hash = source_hash('CPP/7zip/UI/FileManager/BrowseDialog.cpp')
size_raw = size_source.read_bytes()
if hashlib.sha256(size_raw).hexdigest() != size_hash:
    raise SystemExit(f'Not the pinned official {VERSION} BrowseDialog.cpp')
size_text = size_raw.decode('utf-8').replace('\r\n', '\n')
size_start = size_text.index('wchar_t *Browse_ConvertSizeToString(UInt64 v, wchar_t *s)\n{')
size_body = size_text[size_start:size_text.index('// Reload changes DirPrefix.', size_start)].rstrip()
body += '\n\n// BrowseDialog.cpp; original source SHA-256: ' + size_hash + '\n' + size_body
header = ('// BrowseDialog2.cpp\n'
          '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          f'// Generated from official 7-Zip {VERSION} by import-temp-browser.py.\n'
          '// Original bounded enumerator; only the POSIX link accessor adapted.\n'
          '// Original source SHA-256: ' + expected + '\n\n')
destination = root / 'src/upstream/TempBrowseEnumerator.inc'
content = (header + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)

# Reuse the original Properties formatter and fresh bounded rescan.
overwrite = source.with_name('OverwriteDialog.cpp')
overwrite_hash = source_hash('CPP/7zip/UI/FileManager/OverwriteDialog.cpp')
if hashlib.sha256(overwrite.read_bytes()).hexdigest() != overwrite_hash:
    raise SystemExit(f'Not the pinned official {VERSION} OverwriteDialog.cpp')
overwrite_text = overwrite.read_text().replace('\r\n', '\n')
size_start = overwrite_text.index('void AddSizeValue(UString &s, UInt64 value)\n{')
properties = overwrite_text[size_start:overwrite_text.index('void COverwriteDialog::SetFileInfoControl(', size_start)].rstrip()
props_start = text.index('static void PrintPropsPrefix(')
properties += '\n\n' + text[props_start:text.index('wchar_t *Browse_ConvertSizeToString', props_start)].rstrip()
props_start = text.index('static void PrintProps_Size(')
properties += '\n\n' + text[props_start:text.index('void CBrowseDialog2::GetSelected_RealIndexes(', props_start)].rstrip()
props_start = text.index('void CBrowseDialog2::PrintFileProps(')
properties += '\n\n' + text[props_start:text.index('void CBrowseDialog2::Show_FileProps_Window(', props_start)].rstrip()
properties = properties.replace('CBrowseDialog2::', 'TempPropertyPrinter::')
properties = properties.replace('fi.Attrib', 'fi.GetWinAttrib()').replace('ConvertUtcFileTimeToString(fi.MTime, t)', 'PortTempTime(fi.MTime, t)')
properties = properties.replace('file2.HasReparsePoint()', 'file2.IsOsSymLink()')
# POSIX directory st_size counts directory storage; Windows FindFile reports 0.
properties = properties.replace('enumer.bi.Size = file2.Size;', 'enumer.bi.Size = file2.IsDir() ? 0 : file2.Size;')
properties_header = ('// BrowseDialog2.cpp / OverwriteDialog.cpp\n'
    '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
    f'// Generated by import-temp-browser.py from official 7-Zip {VERSION}.\n'
    '// Original formatter and rescan; POSIX accessors/time/directory size adapted.\n'
    '// Source SHA-256: ' + expected + '\n// Overwrite SHA-256: ' + overwrite_hash + '\n\n')
properties_destination = root / 'src/upstream/TempBrowseProperties.inc'
properties_content = (properties_header + properties + '\n').encode('utf-8')
if not properties_destination.exists() or properties_destination.read_bytes() != properties_content:
    write_generated(properties_destination, properties_content)
print(properties_destination)
