#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official Agent update bodies with portable boundary adapters."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import hashlib
import pathlib
import sys

root = output_root()
source = pathlib.Path(sys.argv[1]) / 'CPP/7zip/UI/Agent/AgentOut.cpp'
expected = source_hash('CPP/7zip/UI/Agent/AgentOut.cpp')
raw = source.read_bytes()
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit(f'Not the pinned official {VERSION} AgentOut.cpp')
text = raw.decode('utf-8').replace('\r\n', '\n')
start = text.index('HRESULT CAgent::CreateFolder(')
end = text.index('\n\nHRESULT CAgent::RenameItem(', start)
body = text[start:end].rstrip()

def replace(old, new):
    global body
    if body.count(old) != 1:
        raise SystemExit('Expected one CreateFolder anchor: ' + old)
    body = body.replace(old, new)

replace('CAgent::CreateFolder', 'FolderUpdater::CreateFolder')
replace('IFolderArchiveUpdateCallback *updateCallback100', 'IUpdateCallbackUI *updateCallback100')
replace('  CUpdateCallbackAgent updateCallbackAgent;\n  updateCallbackAgent.SetCallback(updateCallback100);',
        '  IUpdateCallbackUI *updateCallbackAgent = updateCallback100;')
replace('  di.Attrib = FILE_ATTRIBUTE_DIRECTORY;', '  di.SetAsDir();')
replace('  if (_proxy2)\n    di.Name = _proxy2->GetDirPath_as_Prefix(_agentFolder->_proxyDirIndex /* , isAltStreamFolder */);\n  else\n    di.Name = _proxy->GetDirPath_as_Prefix(_agentFolder->_proxyDirIndex);',
        '  // The caller supplies the complete logical proxy prefix and name.\n  di.Name.Empty();')
replace('  di.CTime = di.ATime = di.MTime = ft;',
        '  CFiTime portableTime;\n  FILETIME_To_timespec(ft, portableTime);\n  di.CTime = di.ATime = di.MTime = portableTime;')
replace('updateCallback->Callback = &updateCallbackAgent;', 'updateCallback->Callback = updateCallbackAgent;')
header = ('// AgentOut.cpp\n'
          '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          f'// Generated by scripts/import-folder-update.py from official 7-Zip {VERSION}.\n'
          '// CreateFolder body retained; Agent/proxy/UI and POSIX time boundaries adapted.\n'
          '// Original source SHA-256: ' + expected + '\n\n')
destination = root / 'src/upstream/AgentCreateFolder.inc'
content = (header + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)

# Comment changes one real handler item, without expanding its folder/ADS.
start = text.index('HRESULT CAgent::CommentItem(')
end = text.index('\nHRESULT CAgent::UpdateOneFile(', start)
body = text[start:end].rstrip()
replace('CAgent::CommentItem', 'FolderUpdater::CommentItem')
replace('IFolderArchiveUpdateCallback *updateCallback100', 'IUpdateCallbackUI *updateCallback100')
replace('_archiveLink.IsOpen', 'link.IsOpen')
replace('  CUpdateCallbackAgent updateCallbackAgent;\n  updateCallbackAgent.SetCallback(updateCallback100);',
        '  IUpdateCallbackUI *updateCallbackAgent = updateCallback100;')
replace('updateCallback->Callback = &updateCallbackAgent;', 'updateCallback->Callback = updateCallbackAgent;')
destination = root / 'src/upstream/AgentComment.inc'
content = (header.replace('CreateFolder body retained; Agent/proxy/UI and POSIX time boundaries adapted.',
                         'CommentItem body retained; COM/GUI host boundaries adapted.')
           + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)

# Keep UpdateOneFile's original pair construction and name/ADS retention.
start = text.index('HRESULT CAgent::UpdateOneFile(')
end = text.index('\nZ7_COM7F_IMF(CAgent::SetProperties(', start)
body = text[start:end].rstrip()
replace('CAgent::UpdateOneFile', 'FolderUpdater::UpdateOneFile')
replace('IFolderArchiveUpdateCallback *updateCallback100', 'IUpdateCallbackUI *updateCallback100')
replace('  CUpdateCallbackAgent updateCallbackAgent;\n  updateCallbackAgent.SetCallback(updateCallback100);',
        '  IUpdateCallbackUI *updateCallbackAgent = updateCallback100;')
replace('updateCallback->Callback = &updateCallbackAgent;', 'updateCallback->Callback = updateCallbackAgent;')
replace('    dirItems.EnumerateItems2(FString(), UString(), filePaths, NULL);\n    if (dirItems.Items.Size() != 1)',
        '    RINOK(dirItems.EnumerateItems2(FString(), UString(), filePaths, NULL))\n    if (dirItems.Stat.NumErrors || dirItems.Items.Size() != 1 || dirItems.Items[0].IsDir())')
destination = root / 'src/upstream/AgentUpdateOneFile.inc'
content = (header.replace('CreateFolder body retained; Agent/proxy/UI and POSIX time boundaries adapted.',
                         'UpdateOneFile body retained; COM boundary adapted; enumeration failures checked.')
           + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)

# Keep index-based Delete/Rename, including the original Flat/ADS policies.
# Only the COM host and GUI notification boundaries differ on macOS.
operations = []
for name, start_anchor, end_anchor in (
        ('DeleteItems', 'Z7_COM7F_IMF(CAgent::DeleteItems(', '\nHRESULT CAgent::CreateFolder('),
        ('RenameItem', 'HRESULT CAgent::RenameItem(', '\n\nHRESULT CAgent::CommentItem(')):
    start = text.index(start_anchor)
    end = text.index(end_anchor, start)
    body = text[start:end].rstrip()
    if name == 'DeleteItems':
        replace('Z7_COM7F_IMF(CAgent::DeleteItems', 'HRESULT FolderUpdater::DeleteItems')
        replace('IFolderArchiveUpdateCallback *updateCallback100))', 'IUpdateCallbackUI *updateCallback100)')
        replace('        RINOK(updateCallback100->DeleteOperation(deletePath))',
                '        bool isDir = false;\n        RINOK(Archive_IsItem_Dir(GetArchive(), i, isDir))\n        RINOK(updateCallback100->ShowDeleteFile(deletePath, isDir))')
    else:
        replace('CAgent::RenameItem', 'FolderUpdater::RenameItem')
        replace('IFolderArchiveUpdateCallback *updateCallback100', 'IUpdateCallbackUI *updateCallback100')
        replace('_archiveLink.IsOpen', 'link.IsOpen')
    replace('  CUpdateCallbackAgent updateCallbackAgent;\n  updateCallbackAgent.SetCallback(updateCallback100);',
            '  IUpdateCallbackUI *updateCallbackAgent = updateCallback100;')
    replace('updateCallback->Callback = &updateCallbackAgent;', 'updateCallback->Callback = updateCallbackAgent;')
    replace('      realIndices);', '      realIndices);\n  PortSelection::Normalize(realIndices);')
    operations.append(body)
destination = root / 'src/upstream/AgentItemUpdate.inc'
content = (header.replace('CreateFolder body retained; Agent/proxy/UI and POSIX time boundaries adapted.',
                         'DeleteItems/RenameItem bodies retained; COM/GUI boundaries adapted; repeated indices normalized.')
           + '\n\n'.join(operations) + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)

# Keep the Agent's stream boundary as well as its operation body. Handlers
# preserve their own Offset; copying GetGlobalOffset here would duplicate it.
stream_source = pathlib.Path(sys.argv[1]) / 'CPP/7zip/UI/Agent/ArchiveFolderOut.cpp'
stream_expected = source_hash('CPP/7zip/UI/Agent/ArchiveFolderOut.cpp')
stream_raw = stream_source.read_bytes()
if hashlib.sha256(stream_raw).hexdigest() != stream_expected:
    raise SystemExit(f'Not the pinned official {VERSION} ArchiveFolderOut.cpp')
stream_text = stream_raw.decode('utf-8').replace('\r\n', '\n')
start = stream_text.index('    CMyComPtr<IOutStream> tailStream;')
end = stream_text.index('    HRESULT result;', start)
stream_body = stream_text[start:end].rstrip()
anchor = '    const CArc &arc = *_agentSpec->_archiveLink.GetArc();'
if stream_body.count(anchor) != 1 or stream_body.count('tempFile.OutStream') != 3:
    raise SystemExit('Expected official CommonUpdateOperation stream anchors')
stream_body = stream_body.replace(anchor, '').replace('tempFile.OutStream', 'output')
stream_header = ('// ArchiveFolderOut.cpp\n'
                 '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
                 f'// Generated by scripts/import-folder-update.py from official 7-Zip {VERSION}.\n'
                 '// CommonUpdateOperation stream body; opened arc/output boundaries adapted.\n'
                 '// Original source SHA-256: ' + stream_expected + '\n\n')
destination = root / 'src/upstream/AgentUpdateStream.inc'
content = (stream_header + stream_body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)
