#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Reuse the original progress statistics, title and message-list implementations."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
hashes = {
    'ProgressDialog2.cpp': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.cpp'),
    'ProgressDialog2.h': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.h'),
}
notice = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}, generated by import-progress-presentation.py.\n'
sources = {}
for name, expected in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        parser.error('Unsupported original source: ' + name)
    sources[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + expected + '\n'
source = sources['ProgressDialog2.cpp']

def function(signature):
    start = source.index(signature)
    cursor = source.index('{', start) + 1
    depth = 1
    while depth:
        depth += (source[cursor] == '{') - (source[cursor] == '}')
        cursor += 1
    return source[start:cursor]

names = [
    'static void ReduceString(', 'void CProgressDialog::EnableErrorsControls(',
    'void CProgressDialog::SetProgressRange(', 'void CProgressDialog::SetProgressPos(',
    'void CProgressDialog::ShowSize(', 'static void GetChangedString(',
    'static unsigned GetPower32(', 'static unsigned GetPower64(', 'static UInt64 MyMultAndDiv(',
    'void CProgressDialog::UpdateStatInfo(', 'void CProgressDialog::SetTitleText(',
    'void CProgressDialog::SetPauseText(', 'void CProgressDialog::SetPriorityText(',
    'void CProgressDialog::AddMessageDirect(', 'void CProgressDialog::AddMessage(',
    'static unsigned GetNumDigits(', 'void CProgressDialog::UpdateMessagesDialog(',
    'void CProgressDialog::CopyToClipboard(',
]
body = '\n\n'.join(function(name) for name in names)
# Qt provides a monotonic GUI-thread clock instead of Win32 GetTickCount.
body = body.replace('::GetTickCount()', 'GetTickCount()')
# Retain the original overflow-aware helper for all multiplying ratios, not
# only ETA. The original direct products can wrap at large UInt64 values.
body = body.replace('(completed * 1000) / elapsedTime', 'MyMultAndDiv(completed, 1000, elapsedTime)')
body = re.sub(r'percent = progressCompleted \* 100;\s*if \(progressTotal != 0\)\s*percent /= progressTotal;',
              'percent = MyMultAndDiv(progressCompleted, 100, progressTotal);', body)
body = body.replace('packSize * 100 / unpackSize', 'MyMultAndDiv(packSize, 100, unpackSize)')
constants = '\n'.join(line for line in source.splitlines() if line.startswith('static const unsigned kTitleFileNameSizeLimit') or line.startswith('static const unsigned kCurrentFileNameSizeLimit'))
destination = output_root() / 'src/upstream/ProgressPresentation.inc'
write_generated(destination, notice + constants + '\n\n' + body + '\n')
header = sources['ProgressDialog2.h']
start = header.index('class CU64ToI32Converter')
cursor = header.index('{', start) + 1
depth = 1
while depth:
    depth += (header[cursor] == '{') - (header[cursor] == '}')
    cursor += 1
write_generated(destination.parent / 'ProgressConverter.inc', notice + header[start:cursor + 1] + '\n')
print('Imported original progress statistics, titles and message numbering')

references = {
    'UI/FileManager/ExtractCallback.cpp': source_hash('CPP/7zip/UI/FileManager/ExtractCallback.cpp'),
    'UI/GUI/ExtractRes.h': source_hash('CPP/7zip/UI/GUI/ExtractRes.h'),
    'UI/GUI/resource3.h': source_hash('CPP/7zip/UI/GUI/resource3.h'),
    'Archive/IArchive.h': source_hash('CPP/7zip/Archive/IArchive.h'),
    'UI/GUI/UpdateCallbackGUI2.cpp': source_hash('CPP/7zip/UI/GUI/UpdateCallbackGUI2.cpp'),
    'UI/FileManager/FormatUtils.cpp': source_hash('CPP/7zip/UI/FileManager/FormatUtils.cpp'),
}
extra = {}
for name, expected in references.items():
    raw = (args.source / 'CPP/7zip' / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        parser.error('Unsupported original source: ' + name)
    extra[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + expected + '\n'
definitions = ''
for name in ['UI/GUI/ExtractRes.h', 'UI/GUI/resource3.h']:
    for ident, value in re.findall(r'^#define\s+(IDS_\w+)\s+(\d+)\s*$', extra[name], re.M):
        definitions += 'constexpr unsigned ' + ident + ' = ' + value + ';\n'
enum = re.search(r'namespace NOperationResult\s*\{\s*(enum\s*\{.*?\};)', extra['Archive/IArchive.h'], re.S)
definitions += 'namespace NArchive::NExtract::NOperationResult {\n' + enum[1] + '\n}\n'
operation_table = re.search(r'static const UINT k_UpdNotifyLangs\[\]\s*=\s*\{.*?\};', extra['UI/GUI/UpdateCallbackGUI2.cpp'], re.S)[0]
source = extra['UI/FileManager/ExtractCallback.cpp']
signature = 'void SetExtractErrorMessage(Int32 opRes, Int32 encrypted, const wchar_t *fileName, UString &s)\n{'
error_body = function(signature)
source = extra['UI/FileManager/FormatUtils.cpp']
format_body = function('UString MyFormatNew(const UString &format, const UString &argument)')
write_generated(destination.parent / 'ProgressOperationText.inc', notice + definitions + '\n' + operation_table + '\n' + format_body + '\n#define Z7_LANG\n' + error_body + '\n#undef Z7_LANG\n')
