#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import unchanged original Copy/Combine summary formatting functions."""
import argparse
import hashlib
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
hashes = {'App.cpp': 'ffeb0cd42e88bd29038039857631e584410323864aeae8ed361aaed897f50a9b', 'PanelSplitFile.cpp': 'efd5dda96cf3b619d644da8bda0cebebb9414d0520c01cd31507ba3b0dab17f5'}
texts = {}
notice = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03; generated by scripts/import-copy-info.py.\n'
for name, expected in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != expected:
        parser.error('Unsupported original source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + expected + '\n'
def function(text, signature):
    start = text.index(signature); cursor = text.index('{', start) + 1; depth = 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}'); cursor += 1
    return text[start:cursor]
body = '\n'.join(function(texts['App.cpp'], signature) for signature in ['static void AddSizeValue(', 'static void AddValuePair1(', 'void AddValuePair2(UString &s, UINT resourceID, UInt64 num, UInt64 size)\n{', 'UString CPanel::GetItemsInfoString('])
body += '\n' + function(texts['PanelSplitFile.cpp'], 'static void AddInfoFileName(')
(Path(__file__).resolve().parents[1] / 'src/upstream/CopyInfo.inc').write_text(notice + body + '\n')
