#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import original completion policy, Test text and checksum result formatters."""
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip'
hashes = {
    'UI/GUI/resource2.h': 'd73f560322dfe181f93162732a7e03999fb927e7765d885e74d1eeded83dd555',
    'UI/FileManager/ProgressDialog2.cpp': '8d8af91caad471317aa2cea29474ec623405aa0dc4c22f95c100504815073cdc',
    'UI/FileManager/ProgressDialog2.h': 'e7e85b9bc9bf35677a02e5e2bea74cda6625284ccb470d8d8b923e6cfc5d5fbe',
    'UI/GUI/ExtractGUI.cpp': '1e3b54554bc65c234fd6d1a582aa911e20aae0bd9835694a70bc22fd5d9856e9',
    'UI/GUI/HashGUI.cpp': 'c301ff6f0bd8d6ffa440cd8c69ec1aec3cb8bd4729e9d6ce62aaa117a44aa583',
    'UI/FileManager/OverwriteDialog.cpp': '4d012d2c62b5f15ac31cc93d64a3f165c7affe58d989ccb6c0e6856297020f2a',
    'UI/FileManager/ListViewDialog.cpp': '30a3a0da1b2e44400e899a1326361c9712378da42e259861e482ae5b7f6f45a8',
    'UI/FileManager/PropertyNameRes.h': '7ac6a40b0d985aaa98d760f494ec580f39d83d0a0379dbfd9b4c91a1bc8b9334',
    'UI/FileManager/resourceGui.h': '2f29242ede23eabda49d9378402070f22378ddd601db5997ea64e051768a5b42',
    'UI/FileManager/OverwriteDialogRes.h': 'aefa754e55661017bf6316a17903d2abc77683068f00da0d3f876e0696c06535',

}
texts = {}
notice = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03, generated by import-progress-completion.py.\n'
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported original source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + digest + '\n'

def function(source, signature):
    start = source.index(signature); cursor = source.index('{', start) + 1; depth = 1
    while depth:
        depth += (source[cursor] == '{') - (source[cursor] == '}'); cursor += 1
    return source[start:cursor]

destination = Path(__file__).resolve().parents[1] / 'src/upstream'
header = texts['UI/FileManager/ProgressDialog2.h']
pairs = header[header.index('struct CProgressMessageBoxPair'):header.index('class CProgressSync')]
(destination / 'ProgressFinalMessage.inc').write_text(notice + pairs)
(destination / 'ProgressCompletion.inc').write_text(notice + function(texts['UI/FileManager/ProgressDialog2.cpp'], 'bool CProgressDialog::OnExternalCloseMessage()') + '\n')

extract = texts['UI/GUI/ExtractGUI.cpp']
start = extract.index('      UString s;', extract.index('else if (Options->TestMode)'))
end = extract.index('      FinalMessage.OkMessage.Title', start)
test_body = 'static UString FormatTestResult(const CDecompressStat &Stat)\n{\n' + extract[start:end] + '      return s;\n}\n'
hash_source = texts['UI/GUI/HashGUI.cpp']
size_body = function(texts['UI/FileManager/OverwriteDialog.cpp'], 'void AddSizeValue(UString &s, UInt64 value)\n{')
body = size_body + '\n' + '\n'.join(function(extract, name) for name in ['static void AddValuePair(', 'static void AddSizePair(']) + '\n' + test_body
body += '\nstatic const unsigned k_DigestStringSize = k_HashCalc_DigestSize_Max * 2 + k_HashCalc_ExtraSize * 2 + 16;\n'
body += '\n'.join(function(hash_source, name) for name in ['void AddValuePair(CPropNameValPairs', 'void AddSizeValuePair(', 'static void AddHashString(', 'static void AddHashResString(', 'void AddHashBundleRes(CPropNameValPairs', 'void AddHashBundleRes(UString', 'void ShowHashResults(const CPropNameValPairs'])
ids = {}
for name in ['UI/GUI/resource2.h', 'UI/FileManager/PropertyNameRes.h', 'UI/FileManager/resourceGui.h', 'UI/FileManager/OverwriteDialogRes.h']:
    ids.update({key: value for key, value in re.findall(r'^#define\s+(IDS_\w+)\s+(\d+)\s*$', texts[name], re.M)})
existing = set(re.findall(r'constexpr unsigned (\w+)', (destination / 'ProgressOperationText.inc').read_text()))
needed = set(re.findall(r'\bIDS_\w+', body)) - existing
missing = needed - ids.keys()
if missing: parser.error('Missing original resource IDs: ' + ', '.join(sorted(missing)))
definitions = '\n'.join('constexpr unsigned ' + key + ' = ' + ids[key] + ';' for key in sorted(needed))
(destination / 'ProgressResultText.inc').write_text(notice + definitions + '\n' + body + '\n')
(destination / 'ListViewCopy.inc').write_text(notice + function(texts['UI/FileManager/ListViewDialog.cpp'], 'void CListViewDialog::CopyToClipboard()') + '\n')
print('Imported original completion policy, Test/Hash formatting and list Copy')
