#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Retain official default-opening and filename-warning routines."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
files = {
    'CPP/7zip/UI/FileManager/PanelItemOpen.cpp': source_hash('CPP/7zip/UI/FileManager/PanelItemOpen.cpp'),
    'CPP/7zip/UI/Explorer/ContextMenu.cpp': source_hash('CPP/7zip/UI/Explorer/ContextMenu.cpp'),
    'CPP/Common/MyString.cpp': source_hash('CPP/Common/MyString.cpp'),
}
texts = {}
for name, digest in files.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
def function(text, signature):
    start = text.index(signature)
    opening = text.index('{', start)
    cursor, depth = opening + 1, 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}')
        cursor += 1
    return text[start:cursor]
panel, menu, strings = (texts[name] for name in files)
start = panel.index('static const char * const kExeExtensions')
end = panel.index('// bool FindExt', start)
body = [panel[start:end].rstrip(),
        function(strings, 'bool CStringFinder::FindWord_In_LowCaseAsciiList_NoCase'),
        function(menu, 'bool FindExt(const char *p, const UString &name, CStringFinder &finder)\n{'),
        function(panel, 'static bool DoItemAlwaysStart(const UString &name)'),
        function(panel, 'bool CPanel::IsVirus_Message(const UString &name)')]
header = ('// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          f'// Official 7-Zip {VERSION} routines retained; Qt supplies string/message boundaries.\n'
          '// Generated by scripts/import-open-profile.py.\n')
for name, digest in files.items():
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
output = output_root() / 'src/upstream/OpenProfile.inc'
write_generated(output, header + '\n' + '\n\n'.join(body) + '\n')
print(output)
