#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official portable file-menu filtering and drag-effect bodies."""
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
hashes = {
    'MyLoadMenu.cpp': '6a75a8267d755324baf30b47b01b191e97c05f3c48b3bc45ceee3c2d1dd02da5',
    'PanelDrag.cpp': '231ffa6c824c74cd59584802a3f4db94995312ddd81c6dcb43935e55fe90385a',
    'resource.h': '6ef6f65599b1b3be0c7ab9813caa72eaab246f0aedf572fb04ec33a8695b65d1',
}
texts = {}
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')

def function(text, signature):
    start = text.index(signature)
    cursor = text.index('{', start) + 1
    depth = 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}')
        cursor += 1
    return text[start:cursor]

out = Path(__file__).resolve().parents[1] / 'src/upstream'
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
header += '// Official 7-Zip 26.03; generated by scripts/import-panel-menu-drag.py.\n'
for name, digest in hashes.items():
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
body = function(texts['MyLoadMenu.cpp'], 'void CFileMenu::Load(HMENU hMenu, unsigned startPos)')
# Copy the source action adapters into the destination's Qt adapter.
body = body.replace('  CMenu destMenu;', '  CMenu destMenu = g_FileMenu;')
arrays = texts['MyLoadMenu.cpp'][texts['MyLoadMenu.cpp'].index('static const unsigned g_Zvc_IDs[]'):texts['MyLoadMenu.cpp'].index('void CFileMenu::Load(')]
ids = re.findall(r'^#define\s+(IDM_\w+)\s+(\d+)\s*$', texts['resource.h'], re.M)
(out / 'PanelMenu.inc').write_text(header + '\n' + ''.join('constexpr unsigned ' + name + ' = ' + number + ';\n' for name, number in ids) + '\n' + arrays + body)
drag = texts['PanelDrag.cpp']
labels = '\n'.join('constexpr unsigned ' + name + ' = ' + re.search(r'^#define\s+' + name + r'\s+(\d+)', texts['resource.h'], re.M).group(1) + ';' for name in ('IDS_COPY', 'IDS_MOVE', 'IDS_COPY_TO'))
# The Explorer string IDs are also fixed in the pinned official language
# resources used by the port: archive=2321, compress=2324.
labels += '\nconstexpr unsigned IDS_CONTEXT_COMPRESS = 2324;\n'
(out / 'PanelDrag.inc').write_text(header + '\n' + labels + '\n' + function(drag, 'namespace NDragMenu') + '\n\n' + function(drag, 'static DWORD GetEffect_ForKeys(DWORD keyState)') + '\n\n' + function(drag, 'DWORD CDropTarget::GetEffect(DWORD keyState, POINTL /* pt */, DWORD allowedEffect) const') + '\n')
