#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official Lang2 parsing and Language-page information formatting."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP'
hashes = {
    'Common/Lang.cpp': source_hash('CPP/Common/Lang.cpp'),
    'Common/StringToInt.cpp': source_hash('CPP/Common/StringToInt.cpp'),
    '7zip/UI/FileManager/LangPage.cpp': source_hash('CPP/7zip/UI/FileManager/LangPage.cpp'),
    '7zip/UI/FileManager/LangPage.h': source_hash('CPP/7zip/UI/FileManager/LangPage.h'),
}
texts = {}
header = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}; generated by scripts/import-language.py.\n'
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest: parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
def function(text, signature):
    start = text.index(signature); cursor = text.index('{', start) + 1; depth = 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}'); cursor += 1
    return text[start:cursor]
numbers = texts['Common/StringToInt.cpp']
numbers = numbers[numbers.index('static const UInt32 k_UInt32_max'):numbers.index('Int32 ConvertStringToInt32')]
language = texts['Common/Lang.cpp']
page = texts['7zip/UI/FileManager/LangPage.cpp']
info = function(texts['7zip/UI/FileManager/LangPage.h'], 'struct CLangInfo') + ';'
merge = page[page.index('    unsigned numLines = lang._ids.Size();'):page.index('    langInfo.NumLines = numLines + langInfo.ExtraLines.Size();') + len('    langInfo.NumLines = numLines + langInfo.ExtraLines.Size();')]
body = numbers + '\n' + language[language.index('void CLang::Clear()'):]
body += '\n' + info + '\n' + function(page, 'static void NativeLangString')
body += '\nvoid FillLangInfo(CLangInfo &langInfo, const CLang &lang, const CLang &lang_en)\n{\n  UString n;\n' + merge + '\n}\n'
body += '\n' + function(page, 'static void AddVectorToString(') + '\n' + function(page, 'static void AddVectorToString2(') + '\n'
body += '\n' + function(page, 'void CLangPage::ShowLangInfo()') + '\n'
target = output_root() / 'src/upstream/Language.inc'
write_generated(target, header + '\n' + body)
