#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import original callback-display name and size formatting without Win32 UI."""
import hashlib
import sys
from pathlib import Path
source=Path(sys.argv[1])/'CPP/7zip/UI/FileManager/PanelListNotify.cpp'
digest='bd0b4f317539cc63799df8372f7de36d67df9d846e708f5ea1ed5c31fd64677a'
raw=source.read_bytes()
if hashlib.sha256(raw).hexdigest()!=digest: raise SystemExit('Unsupported original PanelListNotify.cpp')
text=raw.decode().replace('\r\n','\n')
def body(signature):
    start=text.index(signature); brace=text.index('{',start); pos=brace+1; depth=1
    while depth:
        depth+=(text[pos]=='{')-(text[pos]=='}'); pos+=1
    return text[start:pos]
header='// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03; generated by scripts/import-panel-display.py.\n// PanelListNotify.cpp SHA-256: '+digest+'\n'
macro=text[text.index('#define INT_TO_STR_SPEC'):text.index('static void ConvertSizeToString')]
name_start=text.index('        unsigned dest = 0;',text.index('  if (propID == kpidName)',text.index('  if (item.cchTextMax < 32)')))
name_end=text.index('        return 0;',name_start)+len('        return 0;')
outputs={'PanelDisplay.inc':macro+body('static void ConvertSizeToString(')+'\n\n'+body('bool IsSizeProp(UINT propID) throw()\n')+'\n','PanelNameDisplay.inc':text[name_start:name_end]+'\n'}
root=Path(__file__).resolve().parents[1]/'src/upstream'
for name,content in outputs.items():
    target=root/name; data=(header+content).encode()
    if not target.exists() or target.read_bytes()!=data: target.write_bytes(data)
