#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Retain official _7vc implementation, replacing only its platform adapters."""
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
raw = (base / 'VerCtrl.cpp').read_bytes()
digest = hashlib.sha256(raw).hexdigest()
# The expected hash is filled from the verified official 26.03 source.
expected = 'c7b970c431408419ed5dee46e5f975353df715198baf6c5277b67946e53a6985'
if digest != expected:
    parser.error('Unsupported official VerCtrl.cpp')
body = raw.decode().replace('\r\n', '\n')
body = body[body.index('static FString ConvertPath_to_Ctrl'):]
resources = (base / 'resource.h').read_text()
ids = re.findall(r'^#define\s+(IDM_VER_\w+)\s+(\d+)\s*$', resources, re.M)
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
header += '// Official 7-Zip 26.03; generated by scripts/import-version-control.py.\n'
header += '// VerCtrl.cpp SHA-256: ' + digest + '\n\n'
target = Path(__file__).resolve().parents[1] / 'src/upstream/VerCtrl.inc'
target.write_text(header + ''.join('constexpr unsigned ' + name + ' = ' + value + ';\n' for name, value in ids) + '\n' + body)
