#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import portable Agent item/folder properties, retaining the original bodies."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import hashlib
import pathlib
import sys

root = output_root()
source = pathlib.Path(sys.argv[1]) / 'CPP/7zip/UI/Agent/Agent.cpp'
expected = source_hash('CPP/7zip/UI/Agent/Agent.cpp')
raw = source.read_bytes()
if hashlib.sha256(raw).hexdigest() != expected:
    raise SystemExit(f'Not the pinned official {VERSION} Agent.cpp')
text = raw.decode('utf-8').replace('\r\n', '\n')
chunks = []
for start, end in [
    ('#define SET_realIndex_AND_dir ', '\nZ7_COM7F_IMF2(UInt64, CAgentFolder::GetItemSize'),
    ('Z7_COM7F_IMF(CAgentFolder::GetProperty(', '\nstatic UInt64 GetUInt64Prop('),
    ('Z7_COM7F_IMF(CAgentFolder::GetFolderProperty(', '\nZ7_COM7F_IMF(CAgentFolder::GetNumberOfFolderProperties('),
]:
    offset = text.index(start)
    chunks.append(text[offset:text.index(end, offset)].rstrip())
body = '\n\n'.join(chunks).replace('CAgentFolder::', 'PortAgentFolder::')
body = body.replace('Z7_COM7F_IMF(PortAgentFolder::GetProperty(UInt32 index, PROPID propID, PROPVARIANT *value))',
                    'HRESULT PortAgentFolder::GetProperty(UInt32 index, PROPID propID, PROPVARIANT *value)')
body = body.replace('Z7_COM7F_IMF(PortAgentFolder::GetFolderProperty(PROPID propID, PROPVARIANT *value))',
                    'HRESULT PortAgentFolder::GetFolderProperty(PROPID propID, PROPVARIANT *value)')
# Those two properties belong to Agent update/host state, not this read-only
# metadata snapshot. The proxy/handler property bodies below are unchanged.
start = body.index('  if (propID == kpidReadOnly)')
end = body.index('  else if (_proxy2)', start)
body = body[:start] + '  if (_proxy2)' + body[end + len('  else if (_proxy2)'):]
header = ('// Agent.cpp\n'
          '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          f'// Generated by scripts/import-agent-properties.py from official 7-Zip {VERSION}.\n'
          '// GetName/GetPrefix/GetFullPrefix/GetProperty/GetFolderProperty bodies.\n'
          '// COM class boundary adapted; host ReadOnly/IsHash state is not serialized.\n'
          '// Original source SHA-256: ' + expected + '\n\n')
destination = root / 'src/upstream/AgentProperties.inc'
content = (header + body + '\n').encode('utf-8')
if not destination.exists() or destination.read_bytes() != content:
    write_generated(destination, content)
print(destination)
