#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Retain official default-opening and filename-warning routines."""
import argparse
import hashlib
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
files = {
    'CPP/7zip/UI/FileManager/PanelItemOpen.cpp': 'e21c806419c66314bed2def3e4e91562991d323bf4530bd403e364b0104251a2',
    'CPP/7zip/UI/Explorer/ContextMenu.cpp': '5fbce9811445620ec35c0f9f22f866b07354c9092d2e1693df51241ea9565ed2',
    'CPP/Common/MyString.cpp': 'ddb3751cfdcc60ed184f20e94732a1934472ce7cbcf87c40ac8d8b91d5f1b9d8',
}
texts = {}
for name, digest in files.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
def function(text, signature):
    start = text.index(signature)
    opening = text.index('{', start)
    cursor, depth = opening + 1, 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}')
        cursor += 1
    return text[start:cursor]
panel, menu, strings = (texts[name] for name in files)
start = panel.index('static const char * const kExeExtensions')
end = panel.index('// bool FindExt', start)
body = [panel[start:end].rstrip(),
        function(strings, 'bool CStringFinder::FindWord_In_LowCaseAsciiList_NoCase'),
        function(menu, 'bool FindExt(const char *p, const UString &name, CStringFinder &finder)\n{'),
        function(panel, 'static bool DoItemAlwaysStart(const UString &name)'),
        function(panel, 'bool CPanel::IsVirus_Message(const UString &name)')]
header = ('// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          '// Official 7-Zip 26.03 routines retained; Qt supplies string/message boundaries.\n'
          '// Generated by scripts/import-open-profile.py.\n')
for name, digest in files.items():
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
output = Path(__file__).resolve().parents[1] / 'src/upstream/OpenProfile.inc'
output.write_text(header + '\n' + '\n\n'.join(body) + '\n')
print(output)
