#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Expand pinned official desktop RC geometry; import the original progress resize body."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import ast
import csv
import hashlib
import re
import subprocess
import tempfile
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip'
hashes = {
    'UI/FileManager/CopyDialog.rc': source_hash('CPP/7zip/UI/FileManager/CopyDialog.rc'),
    'UI/FileManager/CopyDialogRes.h': source_hash('CPP/7zip/UI/FileManager/CopyDialogRes.h'),
    'UI/FileManager/CopyDialog.cpp': source_hash('CPP/7zip/UI/FileManager/CopyDialog.cpp'),
    'UI/FileManager/ComboDialog.rc': source_hash('CPP/7zip/UI/FileManager/ComboDialog.rc'),
    'UI/FileManager/ComboDialogRes.h': source_hash('CPP/7zip/UI/FileManager/ComboDialogRes.h'),
    'UI/FileManager/ComboDialog.cpp': source_hash('CPP/7zip/UI/FileManager/ComboDialog.cpp'),

    'UI/FileManager/AboutDialog.rc': source_hash('CPP/7zip/UI/FileManager/AboutDialog.rc'),
    'UI/FileManager/AboutDialogRes.h': source_hash('CPP/7zip/UI/FileManager/AboutDialogRes.h'),
    'UI/FileManager/AboutDialog.cpp': source_hash('CPP/7zip/UI/FileManager/AboutDialog.cpp'),
    'UI/FileManager/BrowseDialog2.rc': source_hash('CPP/7zip/UI/FileManager/BrowseDialog2.rc'),
    'UI/FileManager/BrowseDialog2Res.h': source_hash('CPP/7zip/UI/FileManager/BrowseDialog2Res.h'),
    'UI/FileManager/BrowseDialog2.cpp': source_hash('CPP/7zip/UI/FileManager/BrowseDialog2.cpp'),
    'UI/FileManager/resource.h': source_hash('CPP/7zip/UI/FileManager/resource.h'),
    'UI/FileManager/EditDialog.cpp': source_hash('CPP/7zip/UI/FileManager/EditDialog.cpp'),
    'UI/FileManager/EditDialog.rc': source_hash('CPP/7zip/UI/FileManager/EditDialog.rc'),
    'UI/FileManager/EditDialogRes.h': source_hash('CPP/7zip/UI/FileManager/EditDialogRes.h'),
    'UI/FileManager/ListViewDialog.cpp': source_hash('CPP/7zip/UI/FileManager/ListViewDialog.cpp'),
    'UI/FileManager/ListViewDialog.rc': source_hash('CPP/7zip/UI/FileManager/ListViewDialog.rc'),
    'UI/FileManager/ListViewDialogRes.h': source_hash('CPP/7zip/UI/FileManager/ListViewDialogRes.h'),
    'UI/GUI/CompressDialog.cpp': source_hash('CPP/7zip/UI/GUI/CompressDialog.cpp'),
    'GuiCommon.rc': source_hash('CPP/7zip/GuiCommon.rc'),
    'UI/GUI/CompressDialog.rc': source_hash('CPP/7zip/UI/GUI/CompressDialog.rc'),
    'UI/GUI/CompressDialogRes.h': source_hash('CPP/7zip/UI/GUI/CompressDialogRes.h'),
    'UI/GUI/CompressOptionsDialog.rc': source_hash('CPP/7zip/UI/GUI/CompressOptionsDialog.rc'),
    'UI/GUI/ExtractDialog.rc': source_hash('CPP/7zip/UI/GUI/ExtractDialog.rc'),
    'UI/GUI/ExtractDialogRes.h': source_hash('CPP/7zip/UI/GUI/ExtractDialogRes.h'),
    'UI/FileManager/ProgressDialog2.rc': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.rc'),
    'UI/FileManager/ProgressDialog2a.rc': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2a.rc'),
    'UI/FileManager/ProgressDialog2Res.h': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2Res.h'),
    'UI/FileManager/ProgressDialog2.cpp': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.cpp'),
}
texts = {}
notice = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION} desktop resources, generated by import-dialog-geometry.py.\n'
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported original source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + digest + '\n'

def integer(expression):
    def visit(node):
        if isinstance(node, ast.Constant) and type(node.value) is int:
            return node.value
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            return -visit(node.operand)
        if isinstance(node, ast.BinOp) and isinstance(node.op, (ast.Add, ast.Sub, ast.Mult)):
            a, b = visit(node.left), visit(node.right)
            return a + b if isinstance(node.op, ast.Add) else a - b if isinstance(node.op, ast.Sub) else a * b
        raise ValueError('Unexpected resource expression: ' + expression)
    return visit(ast.parse(expression.strip(), mode='eval').body)

command = r'LTEXT|RTEXT|CTEXT|GROUPBOX|COMBOBOX|EDITTEXT|PUSHBUTTON|DEFPUSHBUTTON|CONTROL|ICON'
definitions = []
with tempfile.TemporaryDirectory(prefix='7zip-rc-preprocess-') as folder:
    work = Path(folder)
    # Only numeric dialog button identities are supplied. No Windows SDK, font
    # files or system assets are copied; unknown style names stay textual.
    write_generated(work / 'windows.h', '#define IDOK 1\n#define IDCANCEL 2\n#define IDCLOSE 8\n#define IDHELP 9\n')
    write_generated(work / 'CommCtrl.h', '')
    for source, resource_header in [('UI/FileManager/CopyDialog.rc', 'UI/FileManager/CopyDialogRes.h'), ('UI/FileManager/ComboDialog.rc', 'UI/FileManager/ComboDialogRes.h'), ('UI/GUI/CompressDialog.rc', 'UI/GUI/CompressDialogRes.h'), ('UI/GUI/ExtractDialog.rc', 'UI/GUI/ExtractDialogRes.h'), ('UI/FileManager/ProgressDialog2.rc', 'UI/FileManager/ProgressDialog2Res.h'), ('UI/FileManager/ListViewDialog.rc', 'UI/FileManager/ListViewDialogRes.h'), ('UI/FileManager/EditDialog.rc', 'UI/FileManager/EditDialogRes.h'), ('UI/FileManager/AboutDialog.rc', 'UI/FileManager/AboutDialogRes.h'), ('UI/FileManager/BrowseDialog2.rc', 'UI/FileManager/BrowseDialog2Res.h')]:
        extra = ['-include', str(base / 'UI/FileManager/resource.h')] if 'BrowseDialog2' in source else []
        expanded = subprocess.check_output(['clang', '-E', '-P', '-x', 'c', '-I', str(work)] + extra + [str(base / source)], text=True)
        names = {'IDOK': 1, 'IDCANCEL': 2, 'IDCLOSE': 8, 'IDHELP': 9}
        names.update({name: int(value) for name, value in re.findall(r'^#define\s+(\w+)\s+(\d+)\s*$', texts[resource_header], re.M)})
        for match in re.finditer(r'(\d+)\s+DIALOG\s+(.*?)\s+STYLE\s+.*?CAPTION\s+"[^"]*"\s*(?:BEGIN|\{)(.*?)(?:\bEND\b|\})', expanded, re.S):
            ident, bounds, body = match.groups()
            size = [integer(v) for v in bounds.split(',')]
            controls = []; dialog_names = dict(names)
            if 'BrowseDialog2' in source:
                dialog_names.update({name: int(value) for name, value in re.findall(r'^#define\s+(\w+)\s+(\d+)\s*$', texts['UI/FileManager/resource.h'], re.M)})
            for item in re.finditer(r'\b(' + command + r')\s+(.*?)(?=\b(?:' + command + r')\s|\Z)', body, re.S):
                kind, statement = item.groups()
                fields = next(csv.reader([' '.join(statement.splitlines()).strip()], skipinitialspace=True))
                start = 4 if kind == 'CONTROL' else 1 if kind in ('COMBOBOX', 'EDITTEXT') else 2
                control_id = integer(fields[0 if kind in ('COMBOBOX', 'EDITTEXT') else 1])
                rectangle = [integer(v) for v in fields[start:start + 4]]
                if len(rectangle) != 4:
                    raise ValueError('Incomplete RC rectangle: ' + statement)
                if control_id == -1:
                    name = 'STATIC_' + str(len(controls)); control_id = -1000 - len(controls); dialog_names[name] = control_id
                # Win32 combo resource height includes its open popup. Only
                # the closed 14-DLU control participates in the client layout.
                if kind == 'COMBOBOX':
                    rectangle[3] = 14
                controls.append((control_id, kind, rectangle, 'BS_MULTILINE' in statement))
            definitions.append((int(ident), size[2:], controls, dialog_names))

body = ''
for ident, size, controls, names in definitions:
    body += 'static const ResourceDialog dialog_' + str(ident) + '{' + str(ident) + ', {' + ', '.join(map(str, size)) + '}, {\n'
    for control_id, kind, rectangle, multiline in controls:
        body += '    {' + str(control_id) + ', ResourceKind::' + kind + ', {' + ', '.join(map(str, rectangle)) + '}, ' + str(multiline).lower() + '},\n'
    body += '}, {\n'
    for name, value in sorted(names.items()):
        body += '    {"' + name + '", ' + str(value) + '},\n'
    body += '}};\n'
body += 'static const ResourceDialog *const dialogs[]{' + ', '.join('&dialog_' + str(d[0]) for d in definitions) + '};\n'
destination = output_root() / 'src/upstream'
write_generated(destination / 'DialogGeometry.inc', notice + body)

progress = texts['UI/FileManager/ProgressDialog2.cpp']
def function(signature):
    start = progress.index(signature)
    cursor = progress.index('{', start) + 1
    depth = 1
    while depth:
        depth += (progress[cursor] == '{') - (progress[cursor] == '}')
        cursor += 1
    return progress[start:cursor]
array = re.search(r'static const (?:unsigned|UInt32|UINT|int) kIDs\[\]\s*=\s*\{.*?\};', progress, re.S)
if not array:
    parser.error('Original progress control-pair table not found')
write_generated(destination / 'ProgressLayout.inc', notice + array.group() + '\n' + function('bool CProgressDialog::OnSize(') + '\n')
progress = texts['UI/FileManager/ListViewDialog.cpp']
write_generated(destination / 'ListViewLayout.inc', notice + function('bool CListViewDialog::OnSize(') + '\n')
progress = texts['UI/FileManager/EditDialog.cpp']
write_generated(destination / 'EditLayout.inc', notice + '#define MY_CLOSE_BUTTON_ID IDCLOSE\n' + function('bool CEditDialog::OnSize(') + '\n#undef MY_CLOSE_BUTTON_ID\n')
progress = texts['UI/FileManager/ComboDialog.cpp']
write_generated(destination / 'ComboLayout.inc', notice + function('bool CComboDialog::OnSize(') + '\n')
progress = texts['UI/FileManager/CopyDialog.cpp']
write_generated(destination / 'CopyLayout.inc', notice + function('bool CCopyDialog::OnSize(') + '\n')
progress = texts['UI/FileManager/BrowseDialog2.cpp']
write_generated(destination / 'TempBrowseLayout.inc', notice + function('bool CBrowseDialog2::OnSize(') + '\n')
progress = texts['UI/FileManager/ProgressDialog2.cpp']
print('Imported desktop dialog IDs:', ', '.join(str(d[0]) for d in definitions))

compression = texts['UI/GUI/CompressDialog.cpp']
def compression_function(signature):
    start = compression.index(signature); cursor = compression.index('{', start) + 1; depth = 1
    while depth:
        depth += (compression[cursor] == '{') - (compression[cursor] == '}'); cursor += 1
    return compression[start:cursor]
write_generated(destination / 'CompressOptionsText.inc', notice + '\n'.join(compression_function(name) for name in ['static void AddText_from_BoolPair(', 'static void AddText_from_Bool1(', 'void CCompressDialog::ShowOptionsString()']) + '\n')

macro = next(line for line in progress.splitlines() if line.startswith('#define UINT_TO_STR_2'))
speed_start = progress.index('        Byte c = 0;', progress.index('UInt64 v = (completed * 1000)'))
speed_end = progress.index('        if (moveBits != _prevSpeed_MoveBits', speed_start)
format_start = progress.index('          ConvertUInt64ToString(v, s);', speed_end)
format_end = progress.index('          SetItemText(IDT_PROGRESS_SPEED_VAL, s);', format_start)
speed_body = 'static void ConvertSpeedToString(UInt64 v, wchar_t *s)\n{\n' + progress[speed_start:speed_end] + progress[format_start:format_end] + '}\n'
write_generated(destination / 'ProgressText.inc', notice + macro + '\n' + function('void GetTimeString(UInt64 timeValue, wchar_t *s)\n{') + '\n' + function('static void ConvertSizeToString(') + '\n' + speed_body + '#undef UINT_TO_STR_2\n')
