#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Retain official _7vc implementation, replacing only its platform adapters."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI/FileManager'
raw = (base / 'VerCtrl.cpp').read_bytes()
digest = hashlib.sha256(raw).hexdigest()
# The expected hash is filled from the verified official 26.03 source.
expected = source_hash('CPP/7zip/UI/FileManager/VerCtrl.cpp')
if digest != expected:
    parser.error('Unsupported official VerCtrl.cpp')
body = raw.decode().replace('\r\n', '\n')
body = body[body.index('static FString ConvertPath_to_Ctrl'):]
resources = (base / 'resource.h').read_text()
ids = re.findall(r'^#define\s+(IDM_VER_\w+)\s+(\d+)\s*$', resources, re.M)
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
header += f'// Official 7-Zip {VERSION}; generated by scripts/import-version-control.py.\n'
header += '// VerCtrl.cpp SHA-256: ' + digest + '\n\n'
target = output_root() / 'src/upstream/VerCtrl.inc'
write_generated(target, header + ''.join('constexpr unsigned ' + name + ' = ' + value + ';\n' for name, value in ids) + '\n' + body)
