#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official Lang2 parsing and Language-page information formatting."""
import argparse
import hashlib
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP'
hashes = {
    'Common/Lang.cpp': 'e0ab2c725f4218a1a92f849c107b0a427244b2e637423b73ce95dfa1035681bc',
    'Common/StringToInt.cpp': '94fbc62122c7f609014731103a9fb75199bc786ad2c1d6d79f3d3f150ff8150c',
    '7zip/UI/FileManager/LangPage.cpp': '8ec367443726cdb97320a1dcd2a54da55bf6e5a4db9a6d043454fcdc95454e4e',
    '7zip/UI/FileManager/LangPage.h': '0bfdd71e66acf325fa3cf1cd9a25dd15b4190a8f30f4bb4a59f150b9d86db10a',
}
texts = {}
header = '// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip 26.03; generated by scripts/import-language.py.\n'
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest: parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'
def function(text, signature):
    start = text.index(signature); cursor = text.index('{', start) + 1; depth = 1
    while depth:
        depth += (text[cursor] == '{') - (text[cursor] == '}'); cursor += 1
    return text[start:cursor]
numbers = texts['Common/StringToInt.cpp']
numbers = numbers[numbers.index('static const UInt32 k_UInt32_max'):numbers.index('Int32 ConvertStringToInt32')]
language = texts['Common/Lang.cpp']
page = texts['7zip/UI/FileManager/LangPage.cpp']
info = function(texts['7zip/UI/FileManager/LangPage.h'], 'struct CLangInfo') + ';'
merge = page[page.index('    unsigned numLines = lang._ids.Size();'):page.index('    langInfo.NumLines = numLines + langInfo.ExtraLines.Size();') + len('    langInfo.NumLines = numLines + langInfo.ExtraLines.Size();')]
body = numbers + '\n' + language[language.index('void CLang::Clear()'):]
body += '\n' + info + '\n' + function(page, 'static void NativeLangString')
body += '\nvoid FillLangInfo(CLangInfo &langInfo, const CLang &lang, const CLang &lang_en)\n{\n  UString n;\n' + merge + '\n}\n'
body += '\n' + function(page, 'static void AddVectorToString(') + '\n' + function(page, 'static void AddVectorToString2(') + '\n'
body += '\n' + function(page, 'void CLangPage::ShowLangInfo()') + '\n'
target = Path(__file__).resolve().parents[1] / 'src/upstream/Language.inc'
target.write_text(header + '\n' + body)
