#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import official panel ordering, column policy and typed comparisons."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
hashes = {
    'CPP/7zip/UI/FileManager/PanelSort.cpp': source_hash('CPP/7zip/UI/FileManager/PanelSort.cpp'),
    'CPP/7zip/UI/FileManager/PanelItems.cpp': source_hash('CPP/7zip/UI/FileManager/PanelItems.cpp'),
    'CPP/7zip/UI/FileManager/FSFolder.cpp': source_hash('CPP/7zip/UI/FileManager/FSFolder.cpp'),
    'CPP/7zip/PropID.h': source_hash('CPP/7zip/PropID.h'),
    'CPP/Windows/PropVariant.cpp': source_hash('CPP/Windows/PropVariant.cpp'),
    'CPP/Windows/PropVariant.h': source_hash('CPP/Windows/PropVariant.h'),
    'CPP/Windows/FileFind.cpp': source_hash('CPP/Windows/FileFind.cpp'),
    'CPP/Common/MyString.cpp': source_hash('CPP/Common/MyString.cpp'),
    'CPP/7zip/UI/Common/PropIDUtils.cpp': source_hash('CPP/7zip/UI/Common/PropIDUtils.cpp'),
}
texts = {}
header = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}; generated by scripts/import-panel-sort.py.\n'
for name, digest in hashes.items():
    raw = (args.source / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported official source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    header += '// ' + name + ' SHA-256: ' + digest + '\n'

def function(text, signature, last=False):
    start = text.rindex(signature) if last else text.index(signature)
    brace = text.index('{', start)
    level = 1
    end = brace + 1
    while level:
        level += (text[end] == '{') - (text[end] == '}')
        end += 1
    return text[start:end]

sort = texts['CPP/7zip/UI/FileManager/PanelSort.cpp']
items = texts['CPP/7zip/UI/FileManager/PanelItems.cpp']
variant = texts['CPP/Windows/PropVariant.cpp']
chunks = [function(sort, 'int CompareFileNames_ForFolderList('),
          function(sort, 'static int CompareFileNames_Le16('),
          function(texts['CPP/Common/MyString.cpp'], 'int MyStringCompareNoCase(const wchar_t *'),
          function(variant, 'int CPropVariant::Compare('),
          function(sort, 'int CALLBACK CompareItems(LPARAM lParam1, LPARAM lParam2, LPARAM lpData)\n'),
          function(sort, 'void CPanel::SortItemsWithPropID(', last=True),
          function(items, 'static bool GetColumnVisible('),
          function(items, 'static unsigned GetColumnWidth('),
          function(items, 'static int GetColumnAlign('),
          function(texts['CPP/Windows/FileFind.cpp'], 'UInt32 Get_WinAttribPosix_From_PosixMode(')]
attributes = texts['CPP/7zip/UI/Common/PropIDUtils.cpp']
chunks.append(attributes[attributes.index('static const unsigned kNumWinAtrribFlags'):attributes.index('\n\n\nvoid ConvertPropertyToShortString2')])
variant_header = texts['CPP/Windows/PropVariant.h']
chunks.insert(0, function(variant_header, 'unsigned Get_Ns100() const'))
propids = texts['CPP/7zip/PropID.h']
enum_start = propids.index('enum\n{')
enum_end = propids.index('};', enum_start) + 2
target = output_root() / 'src/upstream'
outputs = {
    'PanelSortIds.h': '#pragma once\nnamespace OfficialSort {\n' + propids[enum_start:enum_end] + '\n}\n',
    'PanelSort.inc': '\n\n'.join(chunks[1:]) + '\n',
    'SortTimePrecision.inc': chunks[0] + '\n',
}
# The original filesystem schema, including optional file-identity columns.
fs = texts['CPP/7zip/UI/FileManager/FSFolder.cpp']
start = fs.index('static const Byte kProps[]')
end = fs.index('};', start) + 2
outputs['FilesystemColumns.inc'] = fs[start:end] + '\n'
for name, body in outputs.items():
    path = target / name
    content = (header + '\n' + body).encode()
    if not path.exists() or path.read_bytes() != content:
        write_generated(path, content)
