#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import the original panel Copy output-name policy at the native boundary."""
import hashlib
import sys
from pathlib import Path

source = Path(sys.argv[1]) / 'CPP/7zip/UI/FileManager/PanelItems.cpp'
digest = '2dc5869e794788b366b1dc7fb6485b362e7b72352c1549303b944693765e2f73'
raw = source.read_bytes()
if hashlib.sha256(raw).hexdigest() != digest:
    raise SystemExit('Unsupported original PanelItems.cpp')
text = raw.decode().replace('\r\n', '\n')
start = text.index('UString CPanel::GetItemName_for_Copy(')
end = text.index('\nvoid CPanel::GetItemName(', start)
body = text[start:end].rstrip().replace('CPanel::', 'PortAgentFolder::')
body = body.replace('GetItemName(itemIndex)', 'GetName(itemIndex)')
body = body.replace('_folder->GetProperty(', 'GetProperty(')
body = body.replace(') const\n', ')\n')
notice = ('// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n'
          '// Official 7-Zip 26.03; generated by scripts/import-copy-name.py.\n'
          '// PanelItems.cpp SHA-256: ' + digest + '\n'
          '// Native folder class/GetName substitute the panel property boundary; its GetProperty is non-const.\n')
destination = Path(__file__).resolve().parents[1] / 'src/upstream/CopyName.inc'
content = (notice + body + '\n').encode()
if not destination.exists() or destination.read_bytes() != content:
    destination.write_bytes(content)
