#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import original completion policy, Test text and checksum result formatters."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip'
hashes = {
    'UI/GUI/resource2.h': source_hash('CPP/7zip/UI/GUI/resource2.h'),
    'UI/FileManager/ProgressDialog2.cpp': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.cpp'),
    'UI/FileManager/ProgressDialog2.h': source_hash('CPP/7zip/UI/FileManager/ProgressDialog2.h'),
    'UI/GUI/ExtractGUI.cpp': source_hash('CPP/7zip/UI/GUI/ExtractGUI.cpp'),
    'UI/GUI/HashGUI.cpp': source_hash('CPP/7zip/UI/GUI/HashGUI.cpp'),
    'UI/FileManager/OverwriteDialog.cpp': source_hash('CPP/7zip/UI/FileManager/OverwriteDialog.cpp'),
    'UI/FileManager/ListViewDialog.cpp': source_hash('CPP/7zip/UI/FileManager/ListViewDialog.cpp'),
    'UI/FileManager/PropertyNameRes.h': source_hash('CPP/7zip/UI/FileManager/PropertyNameRes.h'),
    'UI/FileManager/resourceGui.h': source_hash('CPP/7zip/UI/FileManager/resourceGui.h'),
    'UI/FileManager/OverwriteDialogRes.h': source_hash('CPP/7zip/UI/FileManager/OverwriteDialogRes.h'),

}
texts = {}
notice = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}, generated by import-progress-completion.py.\n'
for name, digest in hashes.items():
    raw = (base / name).read_bytes()
    if hashlib.sha256(raw).hexdigest() != digest:
        parser.error('Unsupported original source: ' + name)
    texts[name] = raw.decode().replace('\r\n', '\n')
    notice += '// ' + name + ' SHA-256: ' + digest + '\n'

def function(source, signature):
    start = source.index(signature); cursor = source.index('{', start) + 1; depth = 1
    while depth:
        depth += (source[cursor] == '{') - (source[cursor] == '}'); cursor += 1
    return source[start:cursor]

destination = output_root() / 'src/upstream'
header = texts['UI/FileManager/ProgressDialog2.h']
pairs = header[header.index('struct CProgressMessageBoxPair'):header.index('class CProgressSync')]
write_generated(destination / 'ProgressFinalMessage.inc', notice + pairs)
write_generated(destination / 'ProgressCompletion.inc', notice + function(texts['UI/FileManager/ProgressDialog2.cpp'], 'bool CProgressDialog::OnExternalCloseMessage()') + '\n')

extract = texts['UI/GUI/ExtractGUI.cpp']
start = extract.index('      UString s;', extract.index('else if (Options->TestMode)'))
end = extract.index('      FinalMessage.OkMessage.Title', start)
test_body = 'static UString FormatTestResult(const CDecompressStat &Stat)\n{\n' + extract[start:end] + '      return s;\n}\n'
hash_source = texts['UI/GUI/HashGUI.cpp']
size_body = function(texts['UI/FileManager/OverwriteDialog.cpp'], 'void AddSizeValue(UString &s, UInt64 value)\n{')
body = size_body + '\n' + '\n'.join(function(extract, name) for name in ['static void AddValuePair(', 'static void AddSizePair(']) + '\n' + test_body
body += '\nstatic const unsigned k_DigestStringSize = k_HashCalc_DigestSize_Max * 2 + k_HashCalc_ExtraSize * 2 + 16;\n'
body += '\n'.join(function(hash_source, name) for name in ['void AddValuePair(CPropNameValPairs', 'void AddSizeValuePair(', 'static void AddHashString(', 'static void AddHashResString(', 'void AddHashBundleRes(CPropNameValPairs', 'void AddHashBundleRes(UString', 'void ShowHashResults(const CPropNameValPairs'])
ids = {}
for name in ['UI/GUI/resource2.h', 'UI/FileManager/PropertyNameRes.h', 'UI/FileManager/resourceGui.h', 'UI/FileManager/OverwriteDialogRes.h']:
    ids.update({key: value for key, value in re.findall(r'^#define\s+(IDS_\w+)\s+(\d+)\s*$', texts[name], re.M)})
existing = set(re.findall(r'constexpr unsigned (\w+)', (destination / 'ProgressOperationText.inc').read_text()))
needed = set(re.findall(r'\bIDS_\w+', body)) - existing
missing = needed - ids.keys()
if missing: parser.error('Missing original resource IDs: ' + ', '.join(sorted(missing)))
definitions = '\n'.join('constexpr unsigned ' + key + ' = ' + ids[key] + ';' for key in sorted(needed))
write_generated(destination / 'ProgressResultText.inc', notice + definitions + '\n' + body + '\n')
write_generated(destination / 'ListViewCopy.inc', notice + function(texts['UI/FileManager/ListViewDialog.cpp'], 'void CListViewDialog::CopyToClipboard()') + '\n')
print('Imported original completion policy, Test/Hash formatting and list Copy')
