#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Import original numeric resource identities for Qt controls."""
from upstream_support import VERSION, source_hash, aggregate_hash, artifact_hash, output_root, write_generated
import argparse
import hashlib
import re
from pathlib import Path
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('source', type=Path)
args = parser.parse_args()
base = args.source / 'CPP/7zip/UI'
files = ['GUI/CompressDialogRes.h', 'GUI/ExtractDialogRes.h', 'FileManager/resource.h', 'FileManager/ProgressDialog2Res.h', 'FileManager/LangPageRes.h', 'FileManager/SettingsPageRes.h', 'FileManager/FoldersPageRes.h', 'FileManager/EditPageRes.h', 'FileManager/MenuPageRes.h', 'FileManager/SystemPageRes.h', 'FileManager/AboutDialogRes.h']
digest = hashlib.sha256()
for name in sorted(files): digest.update(name.encode() + b'\0' + (base / name).read_bytes())
if digest.hexdigest() != aggregate_hash('ui-resources'): parser.error('Unsupported original resource headers')
ids = {}
for name in files:
    for key, value in re.findall(r'^#define\s+((?:IDD|IDT|IDX|IDG|IDR|IDS|IDM|IDB)_\w+)\s+(\d+)\s*$', (base / name).read_text(), re.M):
        if int(value) < 400: continue
        if key in ids and ids[key] != value: parser.error('Conflicting original resource ID: ' + key)
        ids[key] = value
header = f'// Copyright (C) 1999-2026 Igor Pavlov. GNU LGPL-2.1-or-later.\n// Official 7-Zip {VERSION}; generated by scripts/import-ui-resource-ids.py.\n'
header += '// Aggregate source-header SHA-256: ' + digest.hexdigest() + '\n'
body = 'namespace OfficialUi {\n' + ''.join('constexpr unsigned ' + key + ' = ' + value + ';\n' for key, value in sorted(ids.items())) + '}\n'
write_generated(output_root() / 'src/upstream/UiResourceIds.h', header + '#pragma once\n' + body)
